### ISSUE TITLE
String#gsub returns incorrect string.

### ISSUE THREAD

**Issue by dyama** [iij/mruby-regexp-pcre#13]
Hi,

    "foo".gsub /^\s*/, ""
      => "foo" # MRI1.9.1
      => ""    # mruby-regexp-pcre rev.168d189 

In gsub method in string_pcre.rb,

https://github.com/iij/mruby-regexp-pcre/blob/168d189cae530826f5ae8f9a102375f0ef86f20e/mrblib/string_pcre.rb#L49

I found gsub returns an empty string in `r` at line 49.

Thanks.

**Comment by tsahara** [comment]
Fixed by https://github.com/iij/mruby-regexp-pcre/commit/1ee038262aa8e08929b04bce96d1b2addc9974d8.  Thanks!
